version: '3'
# This docker-compose file contains the docker containers for sending syn packages from a client to a nginx server
services:

  gcc:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gccsynfl
    restart: always
    network_mode: "bridge"
    command: tail -f /dev/null

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile_nginx
    cap_add:
      - NET_ADMIN
    container_name: nginxserv
    volumes:
      - /c/Users/andabr/src/syn-flood-detection/templates:/etc/nginx/templates
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80
    restart: always
    network_mode: "bridge"






